language: go
go:
  - "1.11.2"

script:
  - make ci

after_success:
  - make ci-release

deploy:
  provider: releases
  api_key:
    secure: RiPypHDZswmcIMY5vmTb/DbSW1TkBJfvHwxAg4SBj/GaqI5TYjDJ/xkC4Yd/yJ8oFIPDeiMvEdjHT2f0QtAlDaLXHRPyZPpAOFvd1SjN3iMUc2FrnGWgJl+Gts+PJY4/f1cIxKVLjjenf54hbv2X0ad9DmTAVKJCm9xWFtVt/qAKHd7sbRPgonffruDnS8LovD0gchxWh9l8XG+snbIqPp6UJM7d89lr8Rrs1fP5UO8SdJF1T91XxBMc2HNX00g0iJMotihMNNUaz8+aENEt4EqASVhyviWaaN6U6VLn3PO9uFL80SekzBcvvfKYwj9Xec8gWS4L+Cp7XFAajbUCDfiDobfPNiW6b+yJXYOwfQc8Nr80dATJRU0G+0/IbFFKnDiQnkiESP30+bH2WaJNt7WULm/gQDgcofLNut2I3Rn4lNiY8O60d+34F2Veat0l6zD8I7sZ3HKQzIYeoaGXvG58tUxQgiotxZlFhr409zQ4j3xQlYZShEpTJAYSk7QPQWOILpnLSI/9yKdYMgFKXbr4ygJmjN19qpvozyljWDh2UnFCKMKdG8f8CAw0s93uO8xYdTe0beiM+s9LyaCgVZE3qLBE99PJf3GrvtZ5mBTHA6dtx6/pfZu3MHEy3PEBa02BFTekHAMtzziCtN8xFKd+otUJsn8RrzgPBCuuF7k=
  file:
    - "./bin/brigadeterm-darwin-amd64"
    - "./bin/brigadeterm-linux-amd64"
    - "./bin/brigadeterm-windows-amd64.exe"
  skip_cleanup: true
  on:
    tags: true

env:
  - GO111MODULE=on
