// Code generated by mockery v1.0.0
package brigade

import brigade "github.com/Azure/brigade/pkg/brigade"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetProject provides a mock function with given fields: projectID
func (_m *Service) GetProject(projectID string) (*brigade.Project, error) {
	ret := _m.Called(projectID)

	var r0 *brigade.Project
	if rf, ok := ret.Get(0).(func(string) *brigade.Project); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*brigade.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectBuilds provides a mock function with given fields: project
func (_m *Service) GetProjectBuilds(project *brigade.Project) ([]*brigade.Build, error) {
	ret := _m.Called(project)

	var r0 []*brigade.Build
	if rf, ok := ret.Get(0).(func(*brigade.Project) []*brigade.Build); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*brigade.Build)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*brigade.Project) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectLastBuild provides a mock function with given fields: projectID
func (_m *Service) GetProjectLastBuild(projectID string) (*brigade.Build, error) {
	ret := _m.Called(projectID)

	var r0 *brigade.Build
	if rf, ok := ret.Get(0).(func(string) *brigade.Build); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*brigade.Build)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjects provides a mock function with given fields:
func (_m *Service) GetProjects() ([]*brigade.Project, error) {
	ret := _m.Called()

	var r0 []*brigade.Project
	if rf, ok := ret.Get(0).(func() []*brigade.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*brigade.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
